TEMPLATE_FILENAME = 'template.jpg'
EXTENSIONS = ['.jpg', '.png']

RESULT_FILENAME = 'demresult.jpg'

UPPER_FONT = 'times.ttf'
UPPER_SIZE = 45
UPPER_FONT_Y = 390
LOWER_FONT = 'arialbd.ttf'
LOWER_SIZE = 14
LOWER_FONT_Y = 450

TEMPLATE_WIDTH = 574
TEMPLATE_HEIGHT = 522
TEMPLATE_COORDS = (75, 45, 499, 373)
PADDING = 10
